/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "auwhvicpyiwsubucanpb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1d2h2aWNweWl3c3VidWNhbnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1Mjc3ODgsImV4cCI6MjA5NzEwMzc4OH0.Cc-bBW1lEXR1TU4LBjwevvc6cu8OA9gMbK-mKAlpQYg"